<script>
    jQuery(document).ready(function () {
        jQuery.ajax({
            url: "<?php echo Mage::getUrl("urbit/postcode/checksettings")?>",
            type: 'post',
            data: {},
            success: function (response) {
                if (response === "1") {
                    jQuery(".urb-it-validator").show();
                }
            }
        });
    });

    function validatePostcode() {
        var postcode = jQuery('input[name="postal_code"]').val();

        jQuery(".urb-it-validator .success").hide();
        jQuery(".urb-it-validator .failed").hide();

        jQuery.ajax({
            url: "<?php echo Mage::getUrl("urbit/postcode/validate")?>",
            type: 'post',
            data: {
                postcode: postcode
            },
            success: function (response) {
                if (response.hasOwnProperty("inside_delivery_area") && response.inside_delivery_area === "yes") {
                    jQuery(".urb-it-validator .success").show();
                } else {
                    jQuery(".urb-it-validator .failed").show();
                }
            }
        });
    }
</script>
<div class="urb-it-validator">
    <div class="urbit-check-postcode-logo-column">
        <div class="urbit-check-postcode-logo"></div>
    </div>
    <div class="urbit-check-postcode-input-column">
        <div class="urbit-check-postcode-title-wrapper">Can you purchase with urb-it?</div>
        <input name="postal_code" class="urbit-postcode urbit-check-postcode-input" placeholder="Postcode" type="text">
        <input type="button" class="urbit-submit urbit-check-postcode-button" value="Check"
               onclick="validatePostcode(); return false;">
    </div>
    <div class="message success urbit-check-postcode-validation-message">You can shop with Urb-it!</div>
    <div class="message failed urbit-check-postcode-validation-message">Right now, you can not shop with Urb-it on that zip code.
    </div>
</div>